name = "frontend"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-11-25"
site = {bucket = "./build", entry-point = "./svelte-kit/cloudflare-workers/entry.js"}
[build.upload]
format = "service-worker"

